import "@fontsource/dm-sans/400.css";
import "@fontsource/dm-sans/400-italic.css";
import "@fontsource/dm-sans/500.css";
import "@fontsource/dm-sans/600.css";
import "@fontsource/lora/400.css";
import "@fontsource/lora/400-italic.css";
import { createRoot } from "react-dom/client";
import App from "./App";
import "./style.css";
import "./mobile.css";
import "./cockpit.css";
createRoot(document.getElementById("root")!).render(<App />);
